[package]
name = "rustymachine-regression"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
itertools = "0.13.0"
ndarray = "0.16.1"
rand = "0.8.5"
rusty-machine = "0.5.4"
serde = "1.0.215"
serde_derive = "1.0.215"
