[package]
name = "my_burn_app02_custom_csv_dataset"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.15.0", features = ["dataset"] }
csv = "1.3.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde = { version = "1.0.215", features = ["std", "derive"] }
